// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbdPpwaowoq39Vkc9a3wBXrbqcmAXKTXY',
    appId: '1:701683766078:web:2cd2c5ba9935d6c7fc526f',
    messagingSenderId: '701683766078',
    projectId: 'my-note-app123',
    authDomain: 'my-note-app123.firebaseapp.com',
    storageBucket: 'my-note-app123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvfz2gqdwZbee6GYBVYt_9KgRqclrOvhM',
    appId: '1:701683766078:android:fc6403a5e91b3adbfc526f',
    messagingSenderId: '701683766078',
    projectId: 'my-note-app123',
    storageBucket: 'my-note-app123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0dID2z-mQCZ2WB4F_lEstN0qv7WKdrLI',
    appId: '1:701683766078:ios:125a2dea84117046fc526f',
    messagingSenderId: '701683766078',
    projectId: 'my-note-app123',
    storageBucket: 'my-note-app123.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0dID2z-mQCZ2WB4F_lEstN0qv7WKdrLI',
    appId: '1:701683766078:ios:2b2afac9939122abfc526f',
    messagingSenderId: '701683766078',
    projectId: 'my-note-app123',
    storageBucket: 'my-note-app123.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
